version: "3.0"
services:

  db:
    image: mysql
    container_name: eleven_docker
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_eleven
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: www_docker_symfony_eleven
    ports:
      - "8080:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/
      - /var/www/project/vendor/
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: